{% set name = "citation-compass" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/citation_compass-{{ version }}.tar.gz
  sha256: b93c0424c803df7f5b63c85e22e76db322c6d0c1cb0db730aa705d9da69ccc3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - citation_compass
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/lincc-frameworks/citation-compass
  summary: 'A tool for managing and tracking citations in scientific projects'
  description: |
    citation-compass is a tool for managing and tracking citations in scientific projects.
    It provides functionality to help researchers organize and maintain their citation
    information in a structured way.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hombit
    - jeremykubica
